workflows:
  ios-ipa:
    name: iOS IPA for Sideloadly
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Flutter pub get
        script: |
          flutter pub get

      - name: Build iOS app (no codesign)
        script: |
          flutter build ios --release --no-codesign

      - name: Paket jadi .ipa
        script: |
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -R Runner.app Payload/
          zip -r ../Runner.ipa Payload

    artifacts:
      - build/ios/Runner.ipa
